name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Back-end
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}
      - run: |
          cd backend
          pip install -r requirements.txt pytest
          pytest -q

      # Front-end
      - uses: actions/setup-node@v4
        with: {node-version: 20}
      - run: |
          cd frontend
          npm ci
          npm run test -- --run
